return {
  { "rcarriga/nvim-notify" },
  { "lukas-reineke/lsp-format.nvim" },
  { 'glepnir/lspsaga.nvim' },
  { 'onsails/lspkind.nvim' },
  { "williamboman/mason.nvim" },
  { "williamboman/mason-lspconfig.nvim" },
  { 'hrsh7th/cmp-nvim-lsp' },
  { 'hrsh7th/cmp-buffer' },
  { "neovim/nvim-lspconfig" },
  { 'tpope/vim-bundler' },
  { 'tpope/vim-eunuch' },
  { 'tpope/vim-repeat' },
  { 'tpope/vim-surround' },
  { 'tpope/vim-dispatch' },
  { 'jxnblk/vim-mdx-js' },
  { 'tomlion/vim-solidity' },
  { 'jparise/vim-graphql' },
  { 'pantharshit00/vim-prisma' },
  { "lukas-reineke/indent-blankline.nvim" },
  { 'L3MON4D3/LuaSnip' },
  { 'andymass/vim-matchup' },
  { 'nvim-lua/plenary.nvim' },
  { 'kyazdani42/nvim-web-devicons' },
  { 'JoosepAlviste/nvim-ts-context-commentstring' },
  { "b0o/SchemaStore.nvim",                       module = "schemastore" },
}
