# Brew taps first
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
tap "homebrew/services"
tap "phrase/brewed"
tap "stripe/stripe-cli"
tap "superfly/tap"
tap "thoughtbot/formulae"
tap "universal-ctags/universal-ctags"

# Install everything needed using brew
brew "asdf"
brew "coreutils"
brew "fd"
brew "fzf"
brew "gh"
brew "jq"
brew "bat"
brew "git"
brew "git-flow-avh"
brew "graphicsmagick"
brew "hub"
brew "imagemagick"
brew "mas"
brew "neovim", args: ["HEAD"]
brew "node"
brew "openssl@3"
brew "postgresql", restart_service: true
brew "rcm"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "ripgrep"
brew "swiftlint"
brew "the_silver_searcher"
brew "tmux"
brew "universal-ctags", args: ["HEAD"]
brew "watchman"
brew "yarn"
brew "zsh"
brew "bottom"
brew "heroku/brew/heroku"
brew "phrase/brewed/phrase"
brew "thoughtbot/formulae/parity"

# The casks
cask "brave-browser"
cask "chromium"
cask "dropbox"
cask "google-chrome"
cask "iterm2"
cask "ngrok"
cask "notion"
cask "raycast"

# And finally the MAS apps
mas "Magnet", id: 441258766
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
